---
- name: Install PHP
  hosts: all
  su: yes
  become_method: sudo
  gather_facts: true
  tags: [web]
  tasks:
  - name: Update the software package repository
    apt:
    update_cache: yes
  - name: Install PHP
    package:
    name: "{{ item }}"
    state: latest
    with_items:
    - php5
    - php5-mysql
